# Generated by Django 5.2.5 on 2025-09-07 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verificated',
            field=models.UUIDField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
