# Generated by Django 5.2.5 on 2025-09-07 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_verificated_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verificated',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
