# Generated by Django 5.2.5 on 2025-09-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verificated',
            new_name='verification_code',
        ),
    ]
