# Generated by Django 5.2.5 on 2025-09-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_verificated_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verificated',
            field=models.BooleanField(default=True),
        ),
    ]
